version: '2'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    restart: always

  server:
    build: ./src
    volumes:       
      - ./src:/code
    command: bash -c "./run.sh"
    ports:
      - "12345:12345"
    expose:
      - "5432"
    depends_on:
      - db
